
params:
  fastlaneDir: fastlane/metadata/android
  fallbackLanguageCode: en-US
  icLauncher: app/src/main/res/mipmap-xhdpi/ic_launcher.png
  featureGraphicOverlay: false
# some other handy options:
#  github: guardianproject/ripple
#  gitlab: guardianproject/ripple
#  googleplay: my.app.id
#  fdroid: my.app.id
